### ISSUE TITLE
Getting obscure error, cant view on telescope

### ISSUE THREAD

**Issue by mikecornille** [mattsplat/readmore#1]
I downloaded from composer and am using the below in my app...

`Textarea::make('Commodity')->onlyOnIndex()->readMore(),`

I am getting this error: Method Laravel\Nova\Http\Requests\NovaRequest::isCreateOrAttachRequest does not exist.

**Comment by mattsplat** [comment]
What version of Nova are you using?

**Comment by mikecornille** [comment]
2.0.0

**Comment by mattsplat** [comment]
Thanks for letting me know.
Not sure why you're getting that error on version 2 that method should be available. I changed that line so I no longer need that method call.

**Comment by mikecornille** [comment]
Cool, I commented them out in the FieldServiceProvider.php file and it seems to be working well.  When I read more it expands vertically keeping the narrow column width, and in your example the column expands some horizontally, any thoughts?  

`//!$request->isCreateOrAttachRequest() &&`
 `//!$request->isUpdateOrUpdateAttachedRequest() &&`

**Comment by mattsplat** [comment]
If you have a lot of fields showing on your index it's going to shrink the
column width. I'm not sure how you go about altering the default column
widths,
